--{{ Fantasy -- Needs Fantasy Jungle Portal Open
local Meow = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"].main.CanCollide = false game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["1"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["2"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["3"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["4"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["5"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["6"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["7"].ProximityPrompt, 1, true)
wait(0.3)
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"].main.CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube.007"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube.006"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube.005"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube.004"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube.003"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube.001"].CanCollide = false
game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"]["Meshes/magic flower1_Cube"].CanCollide = false
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"].main.CFrame
local Float = Instance.new("Part")
Float.Parent = game.Workspace
Float.Size = Vector3.new(5,1,5)
Float.Anchored = true
Float.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, -3, 0)
wait(0.3)
fireproximityprompt(game:GetService("Workspace").Scripts.Amulets.Collect.Fantasy["8"].ProximityPrompt, 1, true)
wait(0.3)
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = Meow
wait(0.2)
game:GetService("ReplicatedStorage").Events.CraftAmulet:FireServer("Fantasy")
